### PR TITLE
Except thread_id

### PR DESCRIPTION
**Pull request by aalmonte**
Add new message attribute 'thread_id' to except logic to fix drivers replies

### CODE REVIEW

**Review by filippotoso — APPROVED** [review]

**Comment by 04dev04** [comment]
@filippotoso is it working with `Originating Messages`? because for me (before the merge) I used this as a work around for replies but it is not working for messages originating from my page so I have to use the old `FacebookDriver`

**Comment by filippotoso** [comment]
Neither of the changes should impact Originating Messages.

If you use this version of the driver to originate a message, which error do you get from Facebook as response?

**Comment by 04dev04** [comment]
> Neither of the changes should impact Originating Messages.
> 
> If you use this version of the driver to originate a message, which error do you get from Facebook as response?

No errors. Just not sending. Like what happened to replies before.

**Comment by filippotoso** [comment]
The latest version of the Facebook driver works correctly:

```php
    $config = array_merge(
        config('botman.config'),
        ['facebook' => config('botman.facebook', [])]
    );

    $botman = BotManFactory::create($config, new LaravelCache());

    $botman->say('Hello world!', 'recepient-id', FacebookDriver::class);
```

If you get the error_subcode 2018001, go into the developer dashboard and regenerate the token.

**Pull request merged**
