### PR TITLE
fix trying to access offset 0 on type null

### PR DESCRIPTION
**Pull request by apreiml**
fixes https://github.com/botman/driver-facebook/issues/98

### CODE REVIEW

**Comment by stefro** [comment]
+1 on this PR.

**Comment by vesper8** [comment]
@mpociot could you please merge this to make this driver compatible with PHP 7.4?

**Comment by Fuhrmann** [comment]
Could this be merged?

**Comment by gurukota** [comment]
They haven't accepted the pull request

**Comment by feralheart** [comment]
Hi @apreiml,
Thank you for your contribution

**Comment by gurukota** [comment]
Hi @mpociot I'm still having trouble installing the facebook driver

**Pull request merged**
